package com.example.EthanApiPlugin.Utility;


import com.example.EthanApiPlugin.Utility.WidgetIDExt;

public enum WidgetInfoExt
{
	FAIRY_RING_TELEPORT_BUTTON(WidgetIDExt.FAIRY_RING_GROUP_ID, WidgetIDExt.FairyRing.TELEPORT_BUTTON),

	WORLD_SWITCHER_BUTTON(WidgetIDExt.LOGOUT_PANEL_ID, WidgetIDExt.LogoutPanel.WORLD_SWITCHER_BUTTON),
	LOGOUT_BUTTON(WidgetIDExt.LOGOUT_PANEL_ID, WidgetIDExt.LogoutPanel.LOGOUT_BUTTON),

	INVENTORY(WidgetIDExt.INVENTORY_GROUP_ID, 0),
	FRIENDS_LIST(WidgetIDExt.FRIENDS_LIST_GROUP_ID, 0),
	IGNORE_LIST(WidgetIDExt.IGNORE_LIST_GROUP_ID, 0),
	FRIENDS_CHAT(WidgetIDExt.FRIENDS_CHAT_GROUP_ID, 0),
	RAIDING_PARTY(WidgetIDExt.RAIDING_PARTY_GROUP_ID, 0),

	WORLD_MAP_VIEW(WidgetIDExt.WORLD_MAP_GROUP_ID, WidgetIDExt.WorldMap.MAPVIEW),
	WORLD_MAP_OVERVIEW_MAP(WidgetIDExt.WORLD_MAP_GROUP_ID, WidgetIDExt.WorldMap.OVERVIEW_MAP),
	WORLD_MAP_BOTTOM_BAR(WidgetIDExt.WORLD_MAP_GROUP_ID, WidgetIDExt.WorldMap.BOTTOM_BAR),
	WORLD_MAP_SEARCH(WidgetIDExt.WORLD_MAP_GROUP_ID, WidgetIDExt.WorldMap.SEARCH),
	WORLD_MAP_SURFACE_SELECTOR(WidgetIDExt.WORLD_MAP_GROUP_ID, WidgetIDExt.WorldMap.SURFACE_SELECTOR),
	WORLD_MAP_TOOLTIP(WidgetIDExt.WORLD_MAP_GROUP_ID, WidgetIDExt.WorldMap.TOOLTIP),

	CLUE_SCROLL_TEXT(WidgetIDExt.CLUE_SCROLL_GROUP_ID, WidgetIDExt.Cluescroll.CLUE_TEXT),
	CLUE_SCROLL_REWARD_ITEM_CONTAINER(WidgetIDExt.CLUE_SCROLL_REWARD_GROUP_ID, WidgetIDExt.Cluescroll.CLUE_SCROLL_ITEM_CONTAINER),

	EQUIPMENT(WidgetIDExt.EQUIPMENT_GROUP_ID, 0),
	EQUIPMENT_INVENTORY_ITEMS_CONTAINER(WidgetIDExt.EQUIPMENT_INVENTORY_GROUP_ID, WidgetIDExt.Equipment.INVENTORY_ITEM_CONTAINER),

	EMOTE_WINDOW(WidgetIDExt.EMOTES_GROUP_ID, WidgetIDExt.Emotes.EMOTE_WINDOW),
	EMOTE_SCROLL_CONTAINER(WidgetIDExt.EMOTES_GROUP_ID, WidgetIDExt.Emotes.EMOTE_SCROLL_CONTAINER),
	EMOTE_CONTAINER(WidgetIDExt.EMOTES_GROUP_ID, WidgetIDExt.Emotes.EMOTE_CONTAINER),
	EMOTE_SCROLLBAR(WidgetIDExt.EMOTES_GROUP_ID, WidgetIDExt.Emotes.EMOTE_SCROLLBAR),

	MUSIC_WINDOW(WidgetIDExt.MUSIC_GROUP_ID, WidgetIDExt.Music.CONTAINER),
	MUSIC_TRACK_LIST(WidgetIDExt.MUSIC_GROUP_ID, WidgetIDExt.Music.LIST),
	MUSIC_TRACK_SCROLL_CONTAINER(WidgetIDExt.MUSIC_GROUP_ID, WidgetIDExt.Music.SCROLL_CONTAINER),
	MUSIC_TRACK_SCROLLBAR(WidgetIDExt.MUSIC_GROUP_ID, WidgetIDExt.Music.SCROLLBAR),

	DIARY_QUEST_WIDGET_TITLE(WidgetIDExt.DIARY_QUEST_GROUP_ID, WidgetIDExt.Diary.DIARY_TITLE),
	DIARY_QUEST_WIDGET_TEXT(WidgetIDExt.DIARY_QUEST_GROUP_ID, WidgetIDExt.Diary.DIARY_TEXT),

	ACHIEVEMENT_DIARY_SCROLL_TITLE(WidgetIDExt.ACHIEVEMENT_DIARY_SCROLL_GROUP_ID, WidgetIDExt.AchievementDiaryScroll.TITLE),
	ACHIEVEMENT_DIARY_SCROLL_TEXT(WidgetIDExt.ACHIEVEMENT_DIARY_SCROLL_GROUP_ID, WidgetIDExt.AchievementDiaryScroll.TEXT),

	PEST_CONTROL_BOAT_INFO(WidgetIDExt.PEST_CONTROL_BOAT_GROUP_ID, 2),
	PEST_CONTROL_KNIGHT_INFO_CONTAINER(WidgetIDExt.PEST_CONTROL_GROUP_ID, WidgetIDExt.PestControl.KNIGHT_INFO_CONTAINER),
	PEST_CONTROL_ACTIVITY_SHIELD_INFO_CONTAINER(WidgetIDExt.PEST_CONTROL_GROUP_ID, WidgetIDExt.PestControl.ACTIVITY_SHIELD_CONTAINER),
	PEST_CONTROL_PURPLE_SHIELD(WidgetIDExt.PEST_CONTROL_GROUP_ID, WidgetIDExt.PestControl.PURPLE_SHIELD),
	PEST_CONTROL_BLUE_SHIELD(WidgetIDExt.PEST_CONTROL_GROUP_ID, WidgetIDExt.PestControl.BLUE_SHIELD),
	PEST_CONTROL_YELLOW_SHIELD(WidgetIDExt.PEST_CONTROL_GROUP_ID, WidgetIDExt.PestControl.YELLOW_SHIELD),
	PEST_CONTROL_RED_SHIELD(WidgetIDExt.PEST_CONTROL_GROUP_ID, WidgetIDExt.PestControl.RED_SHIELD),
	PEST_CONTROL_PURPLE_HEALTH(WidgetIDExt.PEST_CONTROL_GROUP_ID, WidgetIDExt.PestControl.PURPLE_HEALTH),
	PEST_CONTROL_BLUE_HEALTH(WidgetIDExt.PEST_CONTROL_GROUP_ID, WidgetIDExt.PestControl.BLUE_HEALTH),
	PEST_CONTROL_YELLOW_HEALTH(WidgetIDExt.PEST_CONTROL_GROUP_ID, WidgetIDExt.PestControl.YELLOW_HEALTH),
	PEST_CONTROL_RED_HEALTH(WidgetIDExt.PEST_CONTROL_GROUP_ID, WidgetIDExt.PestControl.RED_HEALTH),
	PEST_CONTROL_PURPLE_ICON(WidgetIDExt.PEST_CONTROL_GROUP_ID, WidgetIDExt.PestControl.PURPLE_ICON),
	PEST_CONTROL_BLUE_ICON(WidgetIDExt.PEST_CONTROL_GROUP_ID, WidgetIDExt.PestControl.BLUE_ICON),
	PEST_CONTROL_YELLOW_ICON(WidgetIDExt.PEST_CONTROL_GROUP_ID, WidgetIDExt.PestControl.YELLOW_ICON),
	PEST_CONTROL_RED_ICON(WidgetIDExt.PEST_CONTROL_GROUP_ID, WidgetIDExt.PestControl.RED_ICON),
	PEST_CONTROL_ACTIVITY_BAR(WidgetIDExt.PEST_CONTROL_GROUP_ID, WidgetIDExt.PestControl.ACTIVITY_BAR),
	PEST_CONTROL_ACTIVITY_PROGRESS(WidgetIDExt.PEST_CONTROL_GROUP_ID, WidgetIDExt.PestControl.ACTIVITY_PROGRESS),

	VOLCANIC_MINE_TIME_LEFT(WidgetIDExt.VOLCANIC_MINE_GROUP_ID, WidgetIDExt.VolcanicMine.TIME_LEFT),
	VOLCANIC_MINE_POINTS(WidgetIDExt.VOLCANIC_MINE_GROUP_ID, WidgetIDExt.VolcanicMine.POINTS),
	VOLCANIC_MINE_STABILITY(WidgetIDExt.VOLCANIC_MINE_GROUP_ID, WidgetIDExt.VolcanicMine.STABILITY),
	VOLCANIC_MINE_PLAYER_COUNT(WidgetIDExt.VOLCANIC_MINE_GROUP_ID, WidgetIDExt.VolcanicMine.PLAYER_COUNT),
	VOLCANIC_MINE_VENTS_INFOBOX_GROUP(WidgetIDExt.VOLCANIC_MINE_GROUP_ID, WidgetIDExt.VolcanicMine.VENTS_INFOBOX_CONTAINER),
	VOLCANIC_MINE_STABILITY_INFOBOX_GROUP(WidgetIDExt.VOLCANIC_MINE_GROUP_ID, WidgetIDExt.VolcanicMine.STABILITY_INFOBOX_CONTAINER),
	VOLCANIC_MINE_VENT_A_PERCENTAGE(WidgetIDExt.VOLCANIC_MINE_GROUP_ID, WidgetIDExt.VolcanicMine.VENT_A_PERCENTAGE),
	VOLCANIC_MINE_VENT_B_PERCENTAGE(WidgetIDExt.VOLCANIC_MINE_GROUP_ID, WidgetIDExt.VolcanicMine.VENT_B_PERCENTAGE),
	VOLCANIC_MINE_VENT_C_PERCENTAGE(WidgetIDExt.VOLCANIC_MINE_GROUP_ID, WidgetIDExt.VolcanicMine.VENT_C_PERCENTAGE),
	VOLCANIC_MINE_VENT_A_STATUS(WidgetIDExt.VOLCANIC_MINE_GROUP_ID, WidgetIDExt.VolcanicMine.VENT_A_STATUS),
	VOLCANIC_MINE_VENT_B_STATUS(WidgetIDExt.VOLCANIC_MINE_GROUP_ID, WidgetIDExt.VolcanicMine.VENT_B_STATUS),
	VOLCANIC_MINE_VENT_C_STATUS(WidgetIDExt.VOLCANIC_MINE_GROUP_ID, WidgetIDExt.VolcanicMine.VENT_C_STATUS),

	FRIEND_CHAT_TITLE(WidgetIDExt.FRIENDS_LIST_GROUP_ID, WidgetIDExt.FriendList.TITLE),
	FRIEND_LIST_FULL_CONTAINER(WidgetIDExt.FRIENDS_LIST_GROUP_ID, WidgetIDExt.FriendList.FULL_CONTAINER),
	FRIEND_LIST_SORT_BY_NAME_BUTTON(WidgetIDExt.FRIENDS_LIST_GROUP_ID, WidgetIDExt.FriendList.SORT_BY_NAME_BUTTON),
	FRIEND_LIST_SORT_BY_LAST_WORLD_CHANGE_BUTTON(WidgetIDExt.FRIENDS_LIST_GROUP_ID, WidgetIDExt.FriendList.SORT_BY_LAST_WORLD_CHANGE_BUTTON),
	FRIEND_LIST_SORT_BY_WORLD_BUTTON(WidgetIDExt.FRIENDS_LIST_GROUP_ID, WidgetIDExt.FriendList.SORT_BY_WORLD_BUTTON),
	FRIEND_LIST_LEGACY_SORT_BUTTON(WidgetIDExt.FRIENDS_LIST_GROUP_ID, WidgetIDExt.FriendList.LEGACY_SORT_BUTTON),
	FRIEND_LIST_NAMES_CONTAINER(WidgetIDExt.FRIENDS_LIST_GROUP_ID, WidgetIDExt.FriendList.NAMES_CONTAINER),
	FRIEND_LIST_SCROLL_BAR(WidgetIDExt.FRIENDS_LIST_GROUP_ID, WidgetIDExt.FriendList.SCROLL_BAR),
	FRIEND_LIST_LOADING_TEXT(WidgetIDExt.FRIENDS_LIST_GROUP_ID, WidgetIDExt.FriendList.LOADING_TEXT),
	FRIEND_LIST_PREVIOUS_NAME_HOLDER(WidgetIDExt.FRIENDS_LIST_GROUP_ID, WidgetIDExt.FriendList.PREVIOUS_NAME_HOLDER),

	IGNORE_TITLE(WidgetIDExt.IGNORE_LIST_GROUP_ID, WidgetIDExt.IgnoreList.TITLE),
	IGNORE_FULL_CONTAINER(WidgetIDExt.IGNORE_LIST_GROUP_ID, WidgetIDExt.IgnoreList.FULL_CONTAINER),
	IGNORE_SORT_BY_NAME_BUTTON(WidgetIDExt.IGNORE_LIST_GROUP_ID, WidgetIDExt.IgnoreList.SORT_BY_NAME_BUTTON),
	IGNORE_LEGACY_SORT_BUTTON(WidgetIDExt.IGNORE_LIST_GROUP_ID, WidgetIDExt.IgnoreList.LEGACY_SORT_BUTTON),
	IGNORE_NAMES_CONTAINER(WidgetIDExt.IGNORE_LIST_GROUP_ID, WidgetIDExt.IgnoreList.NAMES_CONTAINER),
	IGNORE_SCROLL_BAR(WidgetIDExt.IGNORE_LIST_GROUP_ID, WidgetIDExt.IgnoreList.SCROLL_BAR),
	IGNORE_LOADING_TEXT(WidgetIDExt.IGNORE_LIST_GROUP_ID, WidgetIDExt.IgnoreList.LOADING_TEXT),
	IGNORE_PREVIOUS_NAME_HOLDER(WidgetIDExt.IGNORE_LIST_GROUP_ID, WidgetIDExt.IgnoreList.PREVIOUS_NAME_HOLDER),

	EXPLORERS_RING_ALCH_INVENTORY(WidgetIDExt.EXPLORERS_RING_ALCH_GROUP_ID, WidgetIDExt.ExplorersRing.INVENTORY),

	FRIENDS_CHAT_ROOT(WidgetIDExt.FRIENDS_CHAT_GROUP_ID, WidgetIDExt.FriendsChat.ROOT),
	FRIENDS_CHAT_TITLE(WidgetIDExt.FRIENDS_CHAT_GROUP_ID, WidgetIDExt.FriendsChat.TITLE),
	FRIENDS_CHAT_OWNER(WidgetIDExt.FRIENDS_CHAT_GROUP_ID, WidgetIDExt.FriendsChat.OWNER),
	FRIENDS_CHAT_LIST(WidgetIDExt.FRIENDS_CHAT_GROUP_ID, WidgetIDExt.FriendsChat.LIST),

	BANK_CONTAINER(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.BANK_CONTAINER),
	BANK_SEARCH_BUTTON_BACKGROUND(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.SEARCH_BUTTON_BACKGROUND),
	BANK_ITEM_CONTAINER(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.ITEM_CONTAINER),
	BANK_INVENTORY_ITEMS_CONTAINER(WidgetIDExt.BANK_INVENTORY_GROUP_ID, WidgetIDExt.Bank.INVENTORY_ITEM_CONTAINER),
	BANK_TITLE_BAR(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.BANK_TITLE_BAR),
	BANK_INCINERATOR(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.INCINERATOR),
	BANK_INCINERATOR_CONFIRM(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.INCINERATOR_CONFIRM),
	BANK_CONTENT_CONTAINER(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.CONTENT_CONTAINER),
	BANK_DEPOSIT_EQUIPMENT(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.DEPOSIT_EQUIPMENT),
	BANK_DEPOSIT_INVENTORY(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.DEPOSIT_INVENTORY),
	BANK_TAB_CONTAINER(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.TAB_CONTAINER),
	BANK_EQUIPMENT_CONTAINER(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.EQUIPMENT_CONTENT_CONTAINER),
	BANK_EQUIPMENT_BUTTON(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.EQUIPMENT_BUTTON),
	BANK_ITEM_COUNT_TOP(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.ITEM_COUNT_TOP),
	BANK_ITEM_COUNT_BAR(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.ITEM_COUNT_BAR),
	BANK_ITEM_COUNT_BOTTOM(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.ITEM_COUNT_BOTTOM),
	BANK_GROUP_STORAGE_BUTTON(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.GROUP_STORAGE_BUTTON),
	BANK_SCROLLBAR(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.SCROLLBAR),
	BANK_PIN_CONTAINER(WidgetIDExt.BANK_PIN_GROUP_ID, WidgetIDExt.BankPin.CONTAINER),
	BANK_SETTINGS_BUTTON(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.SETTINGS_BUTTON),
	BANK_TUTORIAL_BUTTON(WidgetIDExt.BANK_GROUP_ID, WidgetIDExt.Bank.TUTORIAL_BUTTON),

	GROUP_STORAGE_UI(WidgetIDExt.GROUP_STORAGE_GROUP_ID, WidgetIDExt.GroupStorage.UI),
	GROUP_STORAGE_ITEM_CONTAINER(WidgetIDExt.GROUP_STORAGE_GROUP_ID, WidgetIDExt.GroupStorage.ITEM_CONTAINER),

	GRAND_EXCHANGE_WINDOW_CONTAINER(WidgetIDExt.GRAND_EXCHANGE_GROUP_ID, WidgetIDExt.GrandExchange.WINDOW_CONTAINER),
	GRAND_EXCHANGE_OFFER_CONTAINER(WidgetIDExt.GRAND_EXCHANGE_GROUP_ID, WidgetIDExt.GrandExchange.OFFER_CONTAINER),
	GRAND_EXCHANGE_OFFER_TEXT(WidgetIDExt.GRAND_EXCHANGE_GROUP_ID, WidgetIDExt.GrandExchange.OFFER_DESCRIPTION),

	GRAND_EXCHANGE_INVENTORY_ITEMS_CONTAINER(WidgetIDExt.GRAND_EXCHANGE_INVENTORY_GROUP_ID, WidgetIDExt.GrandExchangeInventory.INVENTORY_ITEM_CONTAINER),

	DEPOSIT_BOX_INVENTORY_ITEMS_CONTAINER(WidgetIDExt.DEPOSIT_BOX_GROUP_ID, WidgetIDExt.DepositBox.INVENTORY_ITEM_CONTAINER),

	SHOP_INVENTORY_ITEMS_CONTAINER(WidgetIDExt.SHOP_INVENTORY_GROUP_ID, WidgetIDExt.Shop.INVENTORY_ITEM_CONTAINER),

	SMITHING_INVENTORY_ITEMS_CONTAINER(WidgetIDExt.SMITHING_GROUP_ID, WidgetIDExt.Smithing.INVENTORY_ITEM_CONTAINER),

	GUIDE_PRICES_ITEMS_CONTAINER(WidgetIDExt.GUIDE_PRICES_GROUP_ID, WidgetIDExt.GuidePrices.ITEM_CONTAINER),
	GUIDE_PRICES_INVENTORY_ITEMS_CONTAINER(WidgetIDExt.GUIDE_PRICES_INVENTORY_GROUP_ID, WidgetIDExt.GuidePrices.INVENTORY_ITEM_CONTAINER),

	RUNE_POUCH_ITEM_CONTAINER(WidgetIDExt.RUNE_POUCH_GROUP_ID, 0),

	MINIMAP_ORBS(WidgetIDExt.MINIMAP_GROUP_ID, 0),
	MINIMAP_XP_ORB(WidgetIDExt.MINIMAP_GROUP_ID, WidgetIDExt.Minimap.XP_ORB),
	MINIMAP_PRAYER_ORB(WidgetIDExt.MINIMAP_GROUP_ID, WidgetIDExt.Minimap.PRAYER_ORB),
	MINIMAP_QUICK_PRAYER_ORB(WidgetIDExt.MINIMAP_GROUP_ID, WidgetIDExt.Minimap.QUICK_PRAYER_ORB),
	MINIMAP_PRAYER_ORB_TEXT(WidgetIDExt.MINIMAP_GROUP_ID, WidgetIDExt.Minimap.PRAYER_ORB_TEXT),
	MINIMAP_RUN_ORB(WidgetIDExt.MINIMAP_GROUP_ID, WidgetIDExt.Minimap.RUN_ORB),
	MINIMAP_TOGGLE_RUN_ORB(WidgetIDExt.MINIMAP_GROUP_ID, WidgetIDExt.Minimap.TOGGLE_RUN_ORB),
	MINIMAP_RUN_ORB_TEXT(WidgetIDExt.MINIMAP_GROUP_ID, WidgetIDExt.Minimap.RUN_ORB_TEXT),
	MINIMAP_HEALTH_ORB(WidgetIDExt.MINIMAP_GROUP_ID, WidgetIDExt.Minimap.HEALTH_ORB),
	MINIMAP_SPEC_ORB(WidgetIDExt.MINIMAP_GROUP_ID, WidgetIDExt.Minimap.SPEC_ORB),
	MINIMAP_WORLDMAP_ORB(WidgetIDExt.MINIMAP_GROUP_ID, WidgetIDExt.Minimap.WORLDMAP_ORB),
	MINIMAP_WIKI_BANNER_PARENT(WidgetIDExt.MINIMAP_GROUP_ID, WidgetIDExt.Minimap.WIKI_BANNER_PARENT),
	MINIMAP_WIKI_BANNER(WidgetIDExt.MINIMAP_GROUP_ID, WidgetIDExt.Minimap.WIKI_BANNER),
	MINIMAP_WORLDMAP_OPTIONS(WidgetIDExt.MINIMAP_GROUP_ID, WidgetIDExt.Minimap.WORLDMAP_OPTIONS),

	LMS_INFO(WidgetIDExt.LMS_GROUP_ID, WidgetIDExt.Lms.INFO),
	LMS_KDA(WidgetIDExt.LMS_INGAME_GROUP_ID, WidgetIDExt.LmsKDA.INFO),

	LOGIN_CLICK_TO_PLAY_SCREEN(WidgetIDExt.LOGIN_CLICK_TO_PLAY_GROUP_ID, 0),
	LOGIN_CLICK_TO_PLAY_SCREEN_MESSAGE_OF_THE_DAY(WidgetIDExt.LOGIN_CLICK_TO_PLAY_GROUP_ID, WidgetIDExt.LoginClickToPlayScreen.MESSAGE_OF_THE_DAY),

	FIXED_VIEWPORT(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.FIXED_VIEWPORT),
	FIXED_VIEWPORT_ROOT_INTERFACE_CONTAINER(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.ROOT_INTERFACE_CONTAINER),
	FIXED_VIEWPORT_BANK_CONTAINER(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.BANK_CONTAINER),
	FIXED_VIEWPORT_INTERFACE_CONTAINER(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.INTERFACE_CONTAINER),
	FIXED_VIEWPORT_INVENTORY_CONTAINER(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.INVENTORY_CONTAINER),
	FIXED_VIEWPORT_COMBAT_TAB(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.COMBAT_TAB),
	FIXED_VIEWPORT_STATS_TAB(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.STATS_TAB),
	FIXED_VIEWPORT_QUESTS_TAB(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.QUESTS_TAB),
	FIXED_VIEWPORT_INVENTORY_TAB(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.INVENTORY_TAB),
	FIXED_VIEWPORT_EQUIPMENT_TAB(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.EQUIPMENT_TAB),
	FIXED_VIEWPORT_PRAYER_TAB(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.PRAYER_TAB),
	FIXED_VIEWPORT_MAGIC_TAB(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.MAGIC_TAB),
	FIXED_VIEWPORT_FRIENDS_CHAT_TAB(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.FRIENDS_CHAT_TAB),
	FIXED_VIEWPORT_FRIENDS_TAB(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.FRIENDS_TAB),
	FIXED_VIEWPORT_IGNORES_TAB(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.IGNORES_TAB),
	FIXED_VIEWPORT_LOGOUT_TAB(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.LOGOUT_TAB),
	FIXED_VIEWPORT_OPTIONS_TAB(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.OPTIONS_TAB),
	FIXED_VIEWPORT_EMOTES_TAB(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.EMOTES_TAB),
	FIXED_VIEWPORT_MUSIC_TAB(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.MUSIC_TAB),
	FIXED_VIEWPORT_COMBAT_ICON(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.COMBAT_ICON),
	FIXED_VIEWPORT_STATS_ICON(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.STATS_ICON),
	FIXED_VIEWPORT_QUESTS_ICON(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.QUESTS_ICON),
	FIXED_VIEWPORT_INVENTORY_ICON(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.INVENTORY_ICON),
	FIXED_VIEWPORT_EQUIPMENT_ICON(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.EQUIPMENT_ICON),
	FIXED_VIEWPORT_PRAYER_ICON(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.PRAYER_ICON),
	FIXED_VIEWPORT_MAGIC_ICON(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.MAGIC_ICON),
	FIXED_VIEWPORT_FRIENDS_CHAT_ICON(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.FRIENDS_CHAT_ICON),
	FIXED_VIEWPORT_FRIENDS_ICON(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.FRIENDS_ICON),
	FIXED_VIEWPORT_IGNORES_ICON(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.IGNORES_ICON),
	FIXED_VIEWPORT_LOGOUT_ICON(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.LOGOUT_ICON),
	FIXED_VIEWPORT_OPTIONS_ICON(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.OPTIONS_ICON),
	FIXED_VIEWPORT_EMOTES_ICON(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.EMOTES_ICON),
	FIXED_VIEWPORT_MUSIC_ICON(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.MUSIC_ICON),
	FIXED_VIEWPORT_MINIMAP(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.MINIMAP),
	FIXED_VIEWPORT_MINIMAP_DRAW_AREA(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.MINIMAP_DRAW_AREA),

	RESIZABLE_MINIMAP_STONES_WIDGET(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.MINIMAP),
	RESIZABLE_MINIMAP_STONES_DRAW_AREA(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.MINIMAP_DRAW_AREA),
	RESIZABLE_MINIMAP_STONES_ORB_HOLDER(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.MINIMAP_ORB_HOLDER),
	RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX),
	RESIZABLE_VIEWPORT_COMBAT_TAB(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.COMBAT_TAB),
	RESIZABLE_VIEWPORT_STATS_TAB(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.STATS_TAB),
	RESIZABLE_VIEWPORT_QUESTS_TAB(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.QUESTS_TAB),
	RESIZABLE_VIEWPORT_INVENTORY_TAB(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.INVENTORY_TAB),
	RESIZABLE_VIEWPORT_EQUIPMENT_TAB(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.EQUIPMENT_TAB),
	RESIZABLE_VIEWPORT_PRAYER_TAB(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.PRAYER_TAB),
	RESIZABLE_VIEWPORT_MAGIC_TAB(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.MAGIC_TAB),
	RESIZABLE_VIEWPORT_FRIENDS_CHAT_TAB(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.FRIENDS_CHAT_TAB),
	RESIZABLE_VIEWPORT_FRIENDS_TAB(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.FRIENDS_TAB),
	RESIZABLE_VIEWPORT_IGNORES_TAB(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.IGNORES_TAB),
	RESIZABLE_VIEWPORT_LOGOUT_TAB(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.LOGOUT_TAB),
	RESIZABLE_VIEWPORT_OPTIONS_TAB(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.OPTIONS_TAB),
	RESIZABLE_VIEWPORT_EMOTES_TAB(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.EMOTES_TAB),
	RESIZABLE_VIEWPORT_MUSIC_TAB(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.MUSIC_TAB),
	RESIZABLE_VIEWPORT_COMBAT_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.COMBAT_ICON),
	RESIZABLE_VIEWPORT_STATS_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.STATS_ICON),
	RESIZABLE_VIEWPORT_QUESTS_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.QUESTS_ICON),
	RESIZABLE_VIEWPORT_INVENTORY_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.INVENTORY_ICON),
	RESIZABLE_VIEWPORT_EQUIPMENT_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.EQUIPMENT_ICON),
	RESIZABLE_VIEWPORT_PRAYER_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.PRAYER_ICON),
	RESIZABLE_VIEWPORT_MAGIC_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.MAGIC_ICON),
	RESIZABLE_VIEWPORT_FRIENDS_CHAT_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.FRIENDS_CHAT_ICON),
	RESIZABLE_VIEWPORT_FRIENDS_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.FRIENDS_ICON),
	RESIZABLE_VIEWPORT_IGNORES_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.IGNORES_ICON),
	RESIZABLE_VIEWPORT_LOGOUT_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.LOGOUT_ICON),
	RESIZABLE_VIEWPORT_OPTIONS_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.OPTIONS_ICON),
	RESIZABLE_VIEWPORT_EMOTES_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.EMOTES_ICON),
	RESIZABLE_VIEWPORT_MUSIC_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.MUSIC_ICON),
	RESIZABLE_VIEWPORT_INTERFACE_CONTAINER(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.INTERFACE_CONTAINER),
	RESIZABLE_VIEWPORT_INVENTORY_CONTAINER(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.INVENTORY_CONTAINER),
	RESIZABLE_VIEWPORT_CHATBOX_PARENT(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.CHATBOX_PARENT),
	RESIZABLE_VIEWPORT_INVENTORY_PARENT(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.INVENTORY_PARENT),

	RESIZABLE_MINIMAP_WIDGET(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.MINIMAP),
	RESIZABLE_MINIMAP_DRAW_AREA(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.MINIMAP_DRAW_AREA),
	RESIZABLE_MINIMAP_ORB_HOLDER(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.MINIMAP_ORB_HOLDER),
	RESIZABLE_MINIMAP_LOGOUT_BUTTON(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.MINIMAP_LOGOUT_BUTTON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.RESIZABLE_VIEWPORT_BOTTOM_LINE),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_LOGOUT_BUTTON(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.LOGOUT_BUTTON_OVERLAY),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_QUESTS_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.QUESTS_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_TAB(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.INVENTORY_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.INVENTORY_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_PRAYER_TAB(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.PRAYER_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_PRAYER_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.PRAYER_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_EQUIPMENT_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.EQUIP_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_COMBAT_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.CMB_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_STATS_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.SKILLS_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_MAGIC_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.MAGIC_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_FRIEND_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.FRIEND_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_FRIEND_CHAT_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.FC_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_OPTIONS_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.SETTINGS_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_EMOTES_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.EMOTE_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_MUSIC_ICON(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.MUSIC_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_CONTAINER(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.INVENTORY_CONTAINER),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INTERFACE_CONTAINER(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.INTERFACE_CONTAINER),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_CHATBOX_PARENT(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.CHATBOX_PARENT),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_TABS1(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.TABS1),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_TABS2(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.TABS2),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_PARENT(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewportBottomLine.INVENTORY_PARENT),

	COMBAT_LEVEL(WidgetIDExt.COMBAT_GROUP_ID, WidgetIDExt.Combat.LEVEL),
	COMBAT_STYLE_ONE(WidgetIDExt.COMBAT_GROUP_ID, WidgetIDExt.Combat.STYLE_ONE),
	COMBAT_STYLE_TWO(WidgetIDExt.COMBAT_GROUP_ID, WidgetIDExt.Combat.STYLE_TWO),
	COMBAT_STYLE_THREE(WidgetIDExt.COMBAT_GROUP_ID, WidgetIDExt.Combat.STYLE_THREE),
	COMBAT_STYLE_FOUR(WidgetIDExt.COMBAT_GROUP_ID, WidgetIDExt.Combat.STYLE_FOUR),
	COMBAT_SPELLS(WidgetIDExt.COMBAT_GROUP_ID, WidgetIDExt.Combat.SPELLS),
	COMBAT_DEFENSIVE_SPELL_BOX(WidgetIDExt.COMBAT_GROUP_ID, WidgetIDExt.Combat.DEFENSIVE_SPELL_BOX),
	COMBAT_DEFENSIVE_SPELL_ICON(WidgetIDExt.COMBAT_GROUP_ID, WidgetIDExt.Combat.DEFENSIVE_SPELL_ICON),
	COMBAT_DEFENSIVE_SPELL_SHIELD(WidgetIDExt.COMBAT_GROUP_ID, WidgetIDExt.Combat.DEFENSIVE_SPELL_SHIELD),
	COMBAT_DEFENSIVE_SPELL_TEXT(WidgetIDExt.COMBAT_GROUP_ID, WidgetIDExt.Combat.DEFENSIVE_SPELL_TEXT),
	COMBAT_SPELL_BOX(WidgetIDExt.COMBAT_GROUP_ID, WidgetIDExt.Combat.SPELL_BOX),
	COMBAT_SPELL_ICON(WidgetIDExt.COMBAT_GROUP_ID, WidgetIDExt.Combat.SPELL_ICON),
	COMBAT_SPELL_TEXT(WidgetIDExt.COMBAT_GROUP_ID, WidgetIDExt.Combat.SPELL_TEXT),
	COMBAT_AUTO_RETALIATE(WidgetIDExt.COMBAT_GROUP_ID, WidgetIDExt.Combat.AUTO_RETALIATE),

	DIALOG_OPTION(WidgetIDExt.DIALOG_OPTION_GROUP_ID, 0),
	DIALOG_OPTION_OPTIONS(WidgetIDExt.DIALOG_OPTION_GROUP_ID, WidgetIDExt.DialogOption.OPTIONS),

	DIALOG_SPRITE(WidgetIDExt.DIALOG_SPRITE_GROUP_ID, 0),
	DIALOG_SPRITE_SPRITE(WidgetIDExt.DIALOG_SPRITE_GROUP_ID, WidgetIDExt.DialogSprite.SPRITE),
	DIALOG_SPRITE_TEXT(WidgetIDExt.DIALOG_SPRITE_GROUP_ID, WidgetIDExt.DialogSprite.TEXT),

	DIALOG_NPC_NAME(WidgetIDExt.DIALOG_NPC_GROUP_ID, WidgetIDExt.DialogNPC.NAME),
	DIALOG_NPC_TEXT(WidgetIDExt.DIALOG_NPC_GROUP_ID, WidgetIDExt.DialogNPC.TEXT),
	DIALOG_NPC_HEAD_MODEL(WidgetIDExt.DIALOG_NPC_GROUP_ID, WidgetIDExt.DialogNPC.HEAD_MODEL),

	DIALOG_PLAYER(WidgetIDExt.DIALOG_PLAYER_GROUP_ID, 0),
	DIALOG_PLAYER_TEXT(WidgetIDExt.DIALOG_PLAYER_GROUP_ID, WidgetIDExt.DialogPlayer.TEXT),

	PRIVATE_CHAT_MESSAGE(WidgetIDExt.PRIVATE_CHAT, 0),

	SLAYER_REWARDS_TOPBAR(WidgetIDExt.SLAYER_REWARDS_GROUP_ID, WidgetIDExt.SlayerRewards.TOP_BAR),

	PRAYER_THICK_SKIN(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.THICK_SKIN),
	PRAYER_BURST_OF_STRENGTH(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.BURST_OF_STRENGTH),
	PRAYER_CLARITY_OF_THOUGHT(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.CLARITY_OF_THOUGHT),
	PRAYER_SHARP_EYE(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.SHARP_EYE),
	PRAYER_MYSTIC_WILL(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.MYSTIC_WILL),
	PRAYER_ROCK_SKIN(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.ROCK_SKIN),
	PRAYER_SUPERHUMAN_STRENGTH(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.SUPERHUMAN_STRENGTH),
	PRAYER_IMPROVED_REFLEXES(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.IMPROVED_REFLEXES),
	PRAYER_RAPID_RESTORE(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.RAPID_RESTORE),
	PRAYER_RAPID_HEAL(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.RAPID_HEAL),
	PRAYER_PROTECT_ITEM(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.PROTECT_ITEM),
	PRAYER_HAWK_EYE(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.HAWK_EYE),
	PRAYER_MYSTIC_LORE(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.MYSTIC_LORE),
	PRAYER_STEEL_SKIN(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.STEEL_SKIN),
	PRAYER_ULTIMATE_STRENGTH(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.ULTIMATE_STRENGTH),
	PRAYER_INCREDIBLE_REFLEXES(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.INCREDIBLE_REFLEXES),
	PRAYER_PROTECT_FROM_MAGIC(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.PROTECT_FROM_MAGIC),
	PRAYER_PROTECT_FROM_MISSILES(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.PROTECT_FROM_MISSILES),
	PRAYER_PROTECT_FROM_MELEE(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.PROTECT_FROM_MELEE),
	PRAYER_EAGLE_EYE(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.EAGLE_EYE),
	PRAYER_MYSTIC_MIGHT(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.MYSTIC_MIGHT),
	PRAYER_RETRIBUTION(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.RETRIBUTION),
	PRAYER_REDEMPTION(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.REDEMPTION),
	PRAYER_SMITE(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.SMITE),
	PRAYER_PRESERVE(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.PRESERVE),
	PRAYER_CHIVALRY(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.CHIVALRY),
	PRAYER_PIETY(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.PIETY),
	PRAYER_RIGOUR(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.RIGOUR),
	PRAYER_AUGURY(WidgetIDExt.PRAYER_GROUP_ID, WidgetIDExt.Prayer.AUGURY),

	//QUICK_PRAYER_PRAYERS(WidgetIDExt.QUICK_PRAYERS_GROUP_ID, WidgetIDExt.QuickPrayer.PRAYERS),



	CHATBOX_PARENT(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.PARENT),
	CHATBOX(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.FRAME),
	CHATBOX_MESSAGES(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.MESSAGES),
	CHATBOX_BUTTONS(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.BUTTONS),
	CHATBOX_TITLE(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.TITLE),
	CHATBOX_FULL_INPUT(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.FULL_INPUT),
	CHATBOX_GE_SEARCH_RESULTS(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.GE_SEARCH_RESULTS),
	CHATBOX_CONTAINER(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.CONTAINER),
	CHATBOX_REPORT_TEXT(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.REPORT_TEXT),
	CHATBOX_INPUT(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.INPUT),
	CHATBOX_TRANSPARENT_BACKGROUND(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.TRANSPARENT_BACKGROUND),
	CHATBOX_TRANSPARENT_LINES(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.TRANSPARENT_BACKGROUND_LINES),
	CHATBOX_MESSAGE_LINES(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.MESSAGE_LINES),
	CHATBOX_FIRST_MESSAGE(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.FIRST_MESSAGE),
	CHATBOX_TAB_ALL(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.TAB_ALL),
	CHATBOX_TAB_GAME(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.TAB_GAME),
	CHATBOX_TAB_PUBLIC(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.TAB_PUBLIC),
	CHATBOX_TAB_PRIVATE(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.TAB_PRIVATE),
	CHATBOX_TAB_CHANNEL(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.TAB_CHANNEL),
	CHATBOX_TAB_CLAN(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.TAB_CLAN),
	CHATBOX_TAB_TRADE(WidgetIDExt.CHATBOX_GROUP_ID, WidgetIDExt.Chatbox.TAB_TRADE),

	BA_TEAM(WidgetIDExt.BA_TEAM_GROUP_ID, WidgetIDExt.BarbarianAssault.TEAM),

	BA_HEAL_ROLE_TEXT(WidgetIDExt.BA_HEALER_GROUP_ID, WidgetIDExt.BarbarianAssault.ROLE),
	BA_HEAL_ROLE_SPRITE(WidgetIDExt.BA_HEALER_GROUP_ID, WidgetIDExt.BarbarianAssault.ROLE_SPRITE),

	BA_HEAL_TEAMMATES(WidgetIDExt.BA_HEALER_GROUP_ID, WidgetIDExt.BarbarianAssault.HLR.TEAMMATES),
	BA_HEAL_TEAMMATE1(WidgetIDExt.BA_HEALER_GROUP_ID, WidgetIDExt.BarbarianAssault.HLR.TEAMMATE1),
	BA_HEAL_TEAMMATE2(WidgetIDExt.BA_HEALER_GROUP_ID, WidgetIDExt.BarbarianAssault.HLR.TEAMMATE2),
	BA_HEAL_TEAMMATE3(WidgetIDExt.BA_HEALER_GROUP_ID, WidgetIDExt.BarbarianAssault.HLR.TEAMMATE3),
	BA_HEAL_TEAMMATE4(WidgetIDExt.BA_HEALER_GROUP_ID, WidgetIDExt.BarbarianAssault.HLR.TEAMMATE4),

	BA_COLL_ROLE_TEXT(WidgetIDExt.BA_COLLECTOR_GROUP_ID, WidgetIDExt.BarbarianAssault.ROLE),
	BA_COLL_ROLE_SPRITE(WidgetIDExt.BA_COLLECTOR_GROUP_ID, WidgetIDExt.BarbarianAssault.ROLE_SPRITE),

	BA_ATK_ROLE_TEXT(WidgetIDExt.BA_ATTACKER_GROUP_ID, WidgetIDExt.BarbarianAssault.ATK.ROLE),
	BA_ATK_ROLE_SPRITE(WidgetIDExt.BA_ATTACKER_GROUP_ID, WidgetIDExt.BarbarianAssault.ATK.ROLE_SPRITE),

	BA_DEF_ROLE_TEXT(WidgetIDExt.BA_DEFENDER_GROUP_ID, WidgetIDExt.BarbarianAssault.ROLE),
	BA_DEF_ROLE_SPRITE(WidgetIDExt.BA_DEFENDER_GROUP_ID, WidgetIDExt.BarbarianAssault.ROLE_SPRITE),

	BA_REWARD_TEXT(WidgetIDExt.BA_REWARD_GROUP_ID, WidgetIDExt.BarbarianAssault.REWARD_TEXT),

	LEVEL_UP(WidgetIDExt.LEVEL_UP_GROUP_ID, 0),
	LEVEL_UP_SKILL(WidgetIDExt.LEVEL_UP_GROUP_ID, WidgetIDExt.LevelUp.SKILL),
	LEVEL_UP_LEVEL(WidgetIDExt.LEVEL_UP_GROUP_ID, WidgetIDExt.LevelUp.LEVEL),

	QUEST_COMPLETED(WidgetIDExt.QUEST_COMPLETED_GROUP_ID, 0),
	QUEST_COMPLETED_NAME_TEXT(WidgetIDExt.QUEST_COMPLETED_GROUP_ID, WidgetIDExt.QuestCompleted.NAME_TEXT),

	MOTHERLODE_MINE(WidgetIDExt.MOTHERLODE_MINE_GROUP_ID, 0),

	GWD_KC(WidgetIDExt.GWD_KC_GROUP_ID, 5),

	PUZZLE_BOX(WidgetIDExt.PUZZLE_BOX_GROUP_ID, WidgetIDExt.PuzzleBox.VISIBLE_BOX),

	LIGHT_BOX(WidgetIDExt.LIGHT_BOX_GROUP_ID, WidgetIDExt.LightBox.LIGHT_BOX),
	LIGHT_BOX_CONTENTS(WidgetIDExt.LIGHT_BOX_GROUP_ID, WidgetIDExt.LightBox.LIGHT_BULB_CONTAINER),
	LIGHT_BOX_BUTTON_A(WidgetIDExt.LIGHT_BOX_GROUP_ID, WidgetIDExt.LightBox.BUTTON_A),
	LIGHT_BOX_BUTTON_B(WidgetIDExt.LIGHT_BOX_GROUP_ID, WidgetIDExt.LightBox.BUTTON_B),
	LIGHT_BOX_BUTTON_C(WidgetIDExt.LIGHT_BOX_GROUP_ID, WidgetIDExt.LightBox.BUTTON_C),
	LIGHT_BOX_BUTTON_D(WidgetIDExt.LIGHT_BOX_GROUP_ID, WidgetIDExt.LightBox.BUTTON_D),
	LIGHT_BOX_BUTTON_E(WidgetIDExt.LIGHT_BOX_GROUP_ID, WidgetIDExt.LightBox.BUTTON_E),
	LIGHT_BOX_BUTTON_F(WidgetIDExt.LIGHT_BOX_GROUP_ID, WidgetIDExt.LightBox.BUTTON_F),
	LIGHT_BOX_BUTTON_G(WidgetIDExt.LIGHT_BOX_GROUP_ID, WidgetIDExt.LightBox.BUTTON_G),
	LIGHT_BOX_BUTTON_H(WidgetIDExt.LIGHT_BOX_GROUP_ID, WidgetIDExt.LightBox.BUTTON_H),

	LIGHT_BOX_WINDOW(WidgetIDExt.LIGHT_BOX_GROUP_ID, WidgetIDExt.LightBox.LIGHT_BOX_WINDOW),

	NIGHTMARE_ZONE(WidgetIDExt.NIGHTMARE_ZONE_GROUP_ID, 0),

	NIGHTMARE_PILLAR_HEALTH(WidgetIDExt.NIGHTMARE_PILLAR_HEALTH_GROUP_ID, 1),

	RAIDS_POINTS_INFOBOX(WidgetIDExt.RAIDS_GROUP_ID, WidgetIDExt.Raids.POINTS_INFOBOX),

	RAIDS_PRIVATE_STORAGE_ITEM_CONTAINER(WidgetIDExt.CHAMBERS_OF_XERIC_STORAGE_UNIT_PRIVATE_GROUP_ID, WidgetIDExt.ChambersOfXericStorageUnitPrivate.PRIVATE_CHEST_ITEM_CONTAINER),

	TOB_PARTY_INTERFACE(WidgetIDExt.TOB_GROUP_ID, WidgetIDExt.Tob.PARTY_INTERFACE),
	TOB_PARTY_STATS(WidgetIDExt.TOB_GROUP_ID, WidgetIDExt.Tob.PARTY_STATS),
	TOB_HEALTH_BAR(WidgetIDExt.TOB_GROUP_ID, WidgetIDExt.Tob.HEALTHBAR_CONTAINER),

	BLAST_FURNACE_COFFER(WidgetIDExt.BLAST_FURNACE_GROUP_ID, 2),

	PYRAMID_PLUNDER_DATA(WidgetIDExt.PYRAMID_PLUNDER_GROUP_ID, 2),

	EXPERIENCE_TRACKER(WidgetIDExt.EXPERIENCE_TRACKER_GROUP_ID, 0),
	EXPERIENCE_TRACKER_WIDGET(WidgetIDExt.EXPERIENCE_TRACKER_GROUP_ID, WidgetIDExt.ExperienceTracker.WIDGET),
	EXPERIENCE_TRACKER_BOTTOM_BAR(WidgetIDExt.EXPERIENCE_TRACKER_GROUP_ID, WidgetIDExt.ExperienceTracker.BOTTOM_BAR),

	FISHING_TRAWLER_CONTRIBUTION(WidgetIDExt.FISHING_TRAWLER_GROUP_ID, 13),
	FISHING_TRAWLER_TIMER(WidgetIDExt.FISHING_TRAWLER_GROUP_ID, 14),

	TITHE_FARM(WidgetIDExt.TITHE_FARM_GROUP_ID, 2),

	BARROWS_BROTHERS(WidgetIDExt.BARROWS_GROUP_ID, WidgetIDExt.Barrows.BARROWS_BROTHERS),
	BARROWS_POTENTIAL(WidgetIDExt.BARROWS_GROUP_ID, WidgetIDExt.Barrows.BARROWS_POTENTIAL),
	BARROWS_PUZZLE_PARENT(WidgetIDExt.BARROWS_PUZZLE_GROUP_ID, WidgetIDExt.Barrows_Puzzle.PARENT),
	BARROWS_PUZZLE_ANSWER1(WidgetIDExt.BARROWS_PUZZLE_GROUP_ID, WidgetIDExt.Barrows_Puzzle.ANSWER1),
	BARROWS_PUZZLE_ANSWER1_CONTAINER(WidgetIDExt.BARROWS_PUZZLE_GROUP_ID, WidgetIDExt.Barrows_Puzzle.ANSWER1_CONTAINER),
	BARROWS_PUZZLE_ANSWER2(WidgetIDExt.BARROWS_PUZZLE_GROUP_ID, WidgetIDExt.Barrows_Puzzle.ANSWER2),
	BARROWS_PUZZLE_ANSWER2_CONTAINER(WidgetIDExt.BARROWS_PUZZLE_GROUP_ID, WidgetIDExt.Barrows_Puzzle.ANSWER2_CONTAINER),
	BARROWS_PUZZLE_ANSWER3(WidgetIDExt.BARROWS_PUZZLE_GROUP_ID, WidgetIDExt.Barrows_Puzzle.ANSWER3),
	BARROWS_PUZZLE_ANSWER3_CONTAINER(WidgetIDExt.BARROWS_PUZZLE_GROUP_ID, WidgetIDExt.Barrows_Puzzle.ANSWER3_CONTAINER),
	BARROWS_FIRST_PUZZLE(WidgetIDExt.BARROWS_PUZZLE_GROUP_ID, WidgetIDExt.Barrows_Puzzle.SEQUENCE_1),

	BLAST_MINE(WidgetIDExt.BLAST_MINE_GROUP_ID, 2),

	FAIRY_RING(WidgetIDExt.FAIRY_RING_GROUP_ID, 0),

	FAIRY_RING_HEADER(WidgetIDExt.FAIRY_RING_PANEL_GROUP_ID, WidgetIDExt.FairyRingPanel.HEADER),
	FAIRY_RING_LIST(WidgetIDExt.FAIRY_RING_PANEL_GROUP_ID, WidgetIDExt.FairyRingPanel.LIST),
	FAIRY_RING_FAVORITES(WidgetIDExt.FAIRY_RING_PANEL_GROUP_ID, WidgetIDExt.FairyRingPanel.FAVORITES),
	FAIRY_RING_LIST_SEPARATOR(WidgetIDExt.FAIRY_RING_PANEL_GROUP_ID, WidgetIDExt.FairyRingPanel.SEPARATOR),
	FAIRY_RING_LIST_SCROLLBAR(WidgetIDExt.FAIRY_RING_PANEL_GROUP_ID, WidgetIDExt.FairyRingPanel.SCROLLBAR),

	DESTROY_ITEM(WidgetIDExt.DESTROY_ITEM_GROUP_ID, 0),
	DESTROY_ITEM_NAME(WidgetIDExt.DESTROY_ITEM_GROUP_ID, WidgetIDExt.DestroyItem.DESTROY_ITEM_NAME),
	DESTROY_ITEM_YES(WidgetIDExt.DESTROY_ITEM_GROUP_ID, WidgetIDExt.DestroyItem.DESTROY_ITEM_YES),
	DESTROY_ITEM_NO(WidgetIDExt.DESTROY_ITEM_GROUP_ID, WidgetIDExt.DestroyItem.DESTROY_ITEM_NO),

	VARROCK_MUSEUM_QUESTION(WidgetIDExt.VARROCK_MUSEUM_QUIZ_GROUP_ID, WidgetIDExt.VarrockMuseum.VARROCK_MUSEUM_QUESTION),
	VARROCK_MUSEUM_FIRST_ANSWER(WidgetIDExt.VARROCK_MUSEUM_QUIZ_GROUP_ID, WidgetIDExt.VarrockMuseum.VARROCK_MUSEUM_FIRST_ANSWER),
	VARROCK_MUSEUM_SECOND_ANSWER(WidgetIDExt.VARROCK_MUSEUM_QUIZ_GROUP_ID, WidgetIDExt.VarrockMuseum.VARROCK_MUSEUM_SECOND_ANSWER),
	VARROCK_MUSEUM_THIRD_ANSWER(WidgetIDExt.VARROCK_MUSEUM_QUIZ_GROUP_ID, WidgetIDExt.VarrockMuseum.VARROCK_MUSEUM_THIRD_ANSWER),

	KILL_LOG_TITLE(WidgetIDExt.KILL_LOGS_GROUP_ID, WidgetIDExt.KillLog.TITLE),
	KILL_LOG_MONSTER(WidgetIDExt.KILL_LOGS_GROUP_ID, WidgetIDExt.KillLog.MONSTER),
	KILL_LOG_KILLS(WidgetIDExt.KILL_LOGS_GROUP_ID, WidgetIDExt.KillLog.KILLS),
	KILL_LOG_STREAK(WidgetIDExt.KILL_LOGS_GROUP_ID, WidgetIDExt.KillLog.STREAK),

	ADVENTURE_LOG(WidgetIDExt.ADVENTURE_LOG_ID, WidgetIDExt.AdventureLog.CONTAINER),

	COLLECTION_LOG(WidgetIDExt.COLLECTION_LOG_ID, WidgetIDExt.CollectionLog.CONTAINER),

	COLLECTION_LOG_TABS(WidgetIDExt.COLLECTION_LOG_ID, WidgetIDExt.CollectionLog.TABS),
	COLLECTION_LOG_ENTRY(WidgetIDExt.COLLECTION_LOG_ID, WidgetIDExt.CollectionLog.ENTRY),
	COLLECTION_LOG_ENTRY_HEADER(WidgetIDExt.COLLECTION_LOG_ID, WidgetIDExt.CollectionLog.ENTRY_HEADER),
	COLLECTION_LOG_ENTRY_ITEMS(WidgetIDExt.COLLECTION_LOG_ID, WidgetIDExt.CollectionLog.ENTRY_ITEMS),

	GENERIC_SCROLL_TEXT(WidgetIDExt.GENERIC_SCROLL_GROUP_ID, WidgetIDExt.GenericScroll.TEXT),

	WORLD_SWITCHER_LIST(WidgetIDExt.WORLD_SWITCHER_GROUP_ID, WidgetIDExt.WorldSwitcher.WORLD_LIST),

	FOSSIL_ISLAND_OXYGENBAR(WidgetIDExt.FOSSIL_ISLAND_OXYGENBAR_ID, 1),

	MINIGAME_TELEPORT_BUTTON(WidgetIDExt.MINIGAME_TAB_ID, WidgetIDExt.Minigames.TELEPORT_BUTTON),

	SPELL_LUMBRIDGE_HOME_TELEPORT(WidgetIDExt.SPELLBOOK_GROUP_ID, WidgetIDExt.StandardSpellBook.LUMBRIDGE_HOME_TELEPORT),
	SPELL_EDGEVILLE_HOME_TELEPORT(WidgetIDExt.SPELLBOOK_GROUP_ID, WidgetIDExt.AncientSpellBook.EDGEVILLE_HOME_TELEPORT),
	SPELL_LUNAR_HOME_TELEPORT(WidgetIDExt.SPELLBOOK_GROUP_ID, WidgetIDExt.LunarSpellBook.LUNAR_HOME_TELEPORT),
	SPELL_ARCEUUS_HOME_TELEPORT(WidgetIDExt.SPELLBOOK_GROUP_ID, WidgetIDExt.ArceuusSpellBook.ARCEUUS_HOME_TELEPORT),
	SPELL_KOUREND_HOME_TELEPORT(WidgetIDExt.SPELLBOOK_GROUP_ID, WidgetIDExt.StandardSpellBook.KOUREND_HOME_TELEPORT),
	SPELL_CATHERBY_HOME_TELEPORT(WidgetIDExt.SPELLBOOK_GROUP_ID, WidgetIDExt.StandardSpellBook.CATHERBY_HOME_TELEPORT),
	SPELL_LUNAR_FERTILE_SOIL(WidgetIDExt.SPELLBOOK_GROUP_ID, WidgetIDExt.LunarSpellBook.FERTILE_SOIL),

	PVP_WILDERNESS_SKULL_CONTAINER(WidgetIDExt.PVP_GROUP_ID, WidgetIDExt.Pvp.WILDERNESS_SKULL_CONTAINER),
	PVP_SKULL_CONTAINER(WidgetIDExt.PVP_GROUP_ID, WidgetIDExt.Pvp.SKULL_CONTAINER),
	PVP_WORLD_SAFE_ZONE(WidgetIDExt.PVP_GROUP_ID, WidgetIDExt.Pvp.SAFE_ZONE),

	PVP_WILDERNESS_LEVEL(WidgetIDExt.PVP_GROUP_ID, WidgetIDExt.Pvp.WILDERNESS_LEVEL),
	PVP_KILLDEATH_COUNTER(WidgetIDExt.PVP_GROUP_ID, WidgetIDExt.Pvp.KILLDEATH_RATIO),

	KOUREND_FAVOUR_OVERLAY(WidgetIDExt.KOUREND_FAVOUR_GROUP_ID, WidgetIDExt.KourendFavour.KOUREND_FAVOUR_OVERLAY),
	ZEAH_MESS_HALL_COOKING_DISPLAY(WidgetIDExt.ZEAH_MESS_HALL_GROUP_ID, WidgetIDExt.Zeah.MESS_HALL_COOKING_DISPLAY),

	LOOTING_BAG_CONTAINER(WidgetIDExt.LOOTING_BAG_GROUP_ID, WidgetIDExt.LootingBag.LOOTING_BAG_INVENTORY),

	SKOTIZO_CONTAINER(WidgetIDExt.SKOTIZO_GROUP_ID, WidgetIDExt.Skotizo.CONTAINER),

	QUESTLIST_BOX(WidgetIDExt.QUESTLIST_GROUP_ID, WidgetIDExt.QuestList.BOX),
	QUESTLIST_CONTAINER(WidgetIDExt.QUESTLIST_GROUP_ID, WidgetIDExt.QuestList.CONTAINER),

	SEED_VAULT_TITLE_CONTAINER(WidgetIDExt.SEED_VAULT_GROUP_ID, WidgetIDExt.SeedVault.TITLE_CONTAINER),
	SEED_VAULT_ITEM_CONTAINER(WidgetIDExt.SEED_VAULT_GROUP_ID, WidgetIDExt.SeedVault.ITEM_CONTAINER),
	SEED_VAULT_ITEM_TEXT(WidgetIDExt.SEED_VAULT_GROUP_ID, WidgetIDExt.SeedVault.ITEM_TEXT),
	SEED_VAULT_INVENTORY_ITEMS_CONTAINER(WidgetIDExt.SEED_VAULT_INVENTORY_GROUP_ID, WidgetIDExt.SeedVault.INVENTORY_ITEM_CONTAINER),

	SETTINGS_SIDE_CAMERA_ZOOM_SLIDER_TRACK(WidgetIDExt.SETTINGS_SIDE_GROUP_ID, WidgetIDExt.SettingsSide.CAMERA_ZOOM_SLIDER_TRACK),
	SETTINGS_SIDE_MUSIC_SLIDER(WidgetIDExt.SETTINGS_SIDE_GROUP_ID, WidgetIDExt.SettingsSide.MUSIC_SLIDER),
	SETTINGS_SIDE_SOUND_EFFECT_SLIDER(WidgetIDExt.SETTINGS_SIDE_GROUP_ID, WidgetIDExt.SettingsSide.SOUND_EFFECT_SLIDER),
	SETTINGS_SIDE_AREA_SOUND_SLIDER(WidgetIDExt.SETTINGS_SIDE_GROUP_ID, WidgetIDExt.SettingsSide.AREA_SOUND_SLIDER),

	SETTINGS_INIT(WidgetIDExt.SETTINGS_GROUP_ID, WidgetIDExt.Settings.INIT),

	ACHIEVEMENT_DIARY_CONTAINER(WidgetIDExt.ACHIEVEMENT_DIARY_GROUP_ID, WidgetIDExt.AchievementDiary.CONTAINER),

	SKILLS_CONTAINER(WidgetIDExt.SKILLS_GROUP_ID, WidgetIDExt.Skills.CONTAINER),

	GAUNTLET_TIMER_CONTAINER(WidgetIDExt.GAUNTLET_TIMER_GROUP_ID, WidgetIDExt.GauntletTimer.CONTAINER),
	HALLOWED_SEPULCHRE_TIMER_CONTAINER(WidgetIDExt.HALLOWED_SEPULCHRE_TIMER_GROUP_ID, WidgetIDExt.HallowedSepulchreTimer.CONTAINER),

	HEALTH_OVERLAY_BAR(WidgetIDExt.HEALTH_OVERLAY_BAR_GROUP_ID, WidgetIDExt.Health.HEALTHBAR_CONTAINER),
	HEALTH_OVERLAY_BAR_TEXT(WidgetIDExt.HEALTH_OVERLAY_BAR_GROUP_ID, WidgetIDExt.Health.HEALTHBAR_TEXT),

	TRAILBLAZER_AREA_TELEPORT(WidgetIDExt.TRAILBLAZER_AREAS_GROUP_ID, WidgetIDExt.TrailblazerAreas.TELEPORT),

	MULTICOMBAT_FIXED(WidgetIDExt.FIXED_VIEWPORT_GROUP_ID, WidgetIDExt.FixedViewport.MULTICOMBAT_INDICATOR),
	MULTICOMBAT_RESIZABLE_MODERN(WidgetIDExt.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExt.ResizableViewport.MULTICOMBAT_INDICATOR),
	MULTICOMBAT_RESIZABLE_CLASSIC(WidgetIDExt.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExt.ResizableViewport.MULTICOMBAT_INDICATOR),

	TEMPOROSS_STATUS_INDICATOR(WidgetIDExt.TEMPOROSS_GROUP_ID, WidgetIDExt.TemporossStatus.STATUS_INDICATOR),

	CLAN_LAYER(WidgetIDExt.CLAN_GROUP_ID, WidgetIDExt.Clan.LAYER),
	CLAN_HEADER(WidgetIDExt.CLAN_GROUP_ID, WidgetIDExt.Clan.HEADER),
	CLAN_MEMBER_LIST(WidgetIDExt.CLAN_GROUP_ID, WidgetIDExt.Clan.MEMBERS),

	CLAN_GUEST_LAYER(WidgetIDExt.CLAN_GUEST_GROUP_ID, WidgetIDExt.ClanGuest.LAYER),
	CLAN_GUEST_HEADER(WidgetIDExt.CLAN_GUEST_GROUP_ID, WidgetIDExt.ClanGuest.HEADER),
	CLAN_GUEST_MEMBER_LIST(WidgetIDExt.CLAN_GUEST_GROUP_ID, WidgetIDExt.ClanGuest.MEMBERS),

	POH_TREASURE_CHEST_INVENTORY_CONTAINER(WidgetIDExt.POH_TREASURE_CHEST_INVENTORY_GROUP_ID, 0),

	TRADE_WINDOW_HEADER(WidgetIDExt.TRADE_WINDOW_GROUP_ID, WidgetIDExt.Trade.HEADER),

	TOA_PARTY_LAYER(WidgetIDExt.TOA_PARTY_GROUP_ID, 2),
	TOA_RAID_LAYER(WidgetIDExt.TOA_RAID_GROUP_ID, 3),
	;

	private final int groupId;
	private final int childId;

	WidgetInfoExt(int groupId, int childId)
	{
		this.groupId = groupId;
		this.childId = childId;
	}

	/**
	 * Gets the ID of the group-child pairing.
	 *
	 * @return the ID
	 */
	public int getId()
	{
		return groupId << 16 | childId;
	}

	/**
	 * Gets the group ID of the pair.
	 *
	 * @return the group ID
	 */
	public int getGroupId()
	{
		return groupId;
	}

	/**
	 * Gets the ID of the child in the group.
	 *
	 * @return the child ID
	 */
	public int getChildId()
	{
		return childId;
	}

	/**
	 * Gets the packed widget ID.
	 *
	 * @return the packed ID
	 */
	public int getPackedId()
	{
		return groupId << 16 | childId;
	}

	/**
	 * Utility method that converts an ID returned by {@link #getId()} back
	 * to its group ID.
	 *
	 * @param id passed group-child ID
	 * @return the group ID
	 */
	public static int TO_GROUP(int id)
	{
		return id >>> 16;
	}

	/**
	 * Utility method that converts an ID returned by {@link #getId()} back
	 * to its child ID.
	 *
	 * @param id passed group-child ID
	 * @return the child ID
	 */
	public static int TO_CHILD(int id)
	{
		return id & 0xFFFF;
	}

	/**
	 * Packs the group and child IDs into a single integer.
	 *
	 * @param groupId the group ID
	 * @param childId the child ID
	 * @return the packed ID
	 */
	public static int PACK(int groupId, int childId)
	{
		return groupId << 16 | childId;
	}

}
