name: EthanApiCompiler

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      run: ./gradlew FatJar

# build/libs/*.jar  # Ruta al archivo JAR compilado por Gradle
        
    - name: Make a release
      id: make_release
      uses: softprops/action-gh-release@v1
      env:
        USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        name: Release ${{ github.sha }}
        body: |
          Automatic release triggered by commit ${GITHUB_SHA}
        files: |
          ./build/libs/*.jar
